In [2]:
import pandas as pd
import numpy as np
import rdkit
from rdkit import Chem
from rdkit.Chem import rdMolDescriptors

In [3]:
descriptor_names = list(rdMolDescriptors.Properties.GetAvailableProperties())

get_descriptors = rdMolDescriptors.Properties(descriptor_names)

def smi_to_descriptors(smile):
    mol = Chem.MolFromSmiles(smile)
    descriptors = []
    if mol:
        descriptors = np.array(get_descriptors.ComputeProperties(mol))
    return descriptors

In [4]:
df = pd.read_csv(r'C:\Users\Anastasia\Documents\GitHub\ophthalmic_drugs\Data\irritation.csv')

In [5]:
df['descriptors'] = df.SMILES.apply(smi_to_descriptors)

In [6]:
df2=df[['descriptors', 'Class']]
df2

                                            descriptors  Class
0     [54.046950192, 54.092, 0.0, 0.0, 0.0, 0.0, 0.0...      1
1     [56.062600255999996, 56.108, 0.0, 0.0, 1.0, 0....      1
2     [58.005479304000005, 58.036, 2.0, 0.0, 1.0, 0....      1
3     [58.041864812, 58.08, 1.0, 0.0, 1.0, 0.0, 1.0,...      1
4     [59.017127284, 59.043, 1.0, 0.0, 0.0, 0.0, 1.0...      1
...                                                 ...    ...
5215  [780.4296067280001, 780.9490000000003, 14.0, 6...      0
5216  [780.4296067280001, 780.9490000000001, 14.0, 6...      0
5217  [788.8541086640001, 789.0990000000004, 11.0, 6...      0
5218  [790.8697587280001, 791.1150000000001, 11.0, 7...      0
5219  [794.4452567920001, 794.9760000000002, 14.0, 5...      0

[5220 rows x 2 columns]

In [7]:
for i in range(len(df['descriptors'][0])):
      df[f'{i}'] = df['descriptors'].apply(lambda x: x[i])

In [8]:
df

,SMILES,Class,descriptors,0,1,2,3,4,5,6,...,33,34,35,36,37,38,39,40,41,42
0,CC#CC,1,"[54.046950192, 54.092, 0.0, 0.0, 0.0, 0.0, 0.0...",54.046950,54.092,0.0,0.0,0.0,0.0,0.0,...,3.000000,1.250000,0.250000,0.250000,0.000000,-0.44,3.560000,2.560000,1.560000,2.278400
1,CCC=C,1,"[56.062600255999996, 56.108, 0.0, 0.0, 1.0, 0....",56.062600,56.108,0.0,0.0,1.0,0.0,0.0,...,2.991564,1.523603,0.288675,0.288675,0.000000,-0.26,3.740000,2.740000,1.740000,2.561900
2,O=CC=O,1,"[58.005479304000005, 58.036, 2.0, 0.0, 1.0, 0....",58.005479,58.036,2.0,0.0,1.0,0.0,2.0,...,1.971197,0.804738,0.055556,0.055556,0.000000,-0.66,3.340000,2.340000,1.340000,1.953900
3,CCC=O,1,"[58.041864812, 58.08, 1.0, 0.0, 1.0, 0.0, 1.0,...",58.041865,58.080,1.0,0.0,1.0,0.0,1.0,...,2.692705,1.351057,0.166667,0.166667,0.000000,-0.33,3.670000,2.670000,1.670000,2.449725
4,FCC#N,1,"[59.017127284, 59.043, 1.0, 0.0, 0.0, 0.0, 1.0...",59.017127,59.043,1.0,0.0,0.0,0.0,1.0,...,2.032285,0.844421,0.059761,0.059761,0.000000,-0.58,3.420000,2.420000,1.420000,2.069100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5215,CC1OC(CC(O)C1O)OC2C(O)CC(OC3C(O)CC(OC4CCC5(C)C...,0,"[780.4296067280001, 780.9490000000003, 14.0, 6...",780.429607,780.949,14.0,6.0,7.0,6.0,14.0,...,32.904204,20.930837,15.818454,15.818454,12.863616,-1.27,40.506603,15.080660,7.050935,11.106660
5216,CC1OC(CC(O)C1O)OC2C(O)CC(OC3C(O)CC(OC4CCC5(C)C...,0,"[780.4296067280001, 780.9490000000001, 14.0, 6...",780.429607,780.949,14.0,6.0,7.0,6.0,14.0,...,32.904204,20.940873,15.951629,15.951629,12.762329,-1.27,40.506603,15.080660,6.950374,11.106660
5217,CN(C(=O)C)c1c(I)c(NC(=O)C)c(I)c(C(=O)NC(C=O)C(...,0,"[788.8541086640001, 789.0990000000004, 11.0, 6...",788.854109,789.099,11.0,6.0,9.0,6.0,8.0,...,17.096813,8.930530,4.373121,4.373121,2.559391,-0.67,29.361918,12.697701,6.687388,11.650902
5218,CC(=O)N(CC(O)CO)c1c(I)c(C(=O)NCCO)c(I)c(C(=O)N...,0,"[790.8697587280001, 791.1150000000001, 11.0, 7...",790.869759,791.115,11.0,7.0,11.0,7.0,8.0,...,16.939261,9.247942,4.108352,4.108352,2.553586,-0.38,29.651626,14.119001,7.568060,13.082854
5219,COC1C(O)CC(OC2C(O)CC(OC3C(O)CC(OC4CCC5(C)C(CCC...,0,"[794.4452567920001, 794.9760000000002, 14.0, 5...",794.445257,794.976,14.0,5.0,8.0,5.0,14.0,...,33.865239,21.326625,16.190510,16.190510,13.102687,-1.27,41.463559,15.641435,7.024560,11.581242

In [9]:
df3 = df.iloc [:, 3:50]
df3.columns = ['exactmw', 'amw', 'lipinskiHBA','lipinskiHBD', 'NumRotatableBonds', 'NumHBD', 'NumHBA', 'NumHeavyAtoms', 'NumAtoms', 'NumHeteroatoms', 'NumAmideBonds', 'FractionCSP3', 'NumRings', 'NumAromaticRings', 'NumAliphaticRings', 'NumSaturatedRings', 'NumHeterocycles', 'NumAromaticHeterocycles', 'NumSaturatedHeterocycles', 'NumAliphaticHeterocycles', 'NumSpiroAtoms', 'NumBridgeheadAtoms', 'NumAtomStereoCenters', 'NumUnspecifiedAtomStereoCenters', 'labuteASA', 'tpsa', 'CrippenClogP', 'CrippenMR', 'chi0v', 'chi1v', 'chi2v', 'chi3v', 'chi4v', 'chi0n', 'chi1n', 'chi2n', 'chi3n', 'chi4n', 'hallKierAlpha', 'kappa1', 'kappa2', 'kappa3', 'Phi']
df3

,exactmw,amw,lipinskiHBA,lipinskiHBD,NumRotatableBonds,NumHBD,NumHBA,NumHeavyAtoms,NumAtoms,NumHeteroatoms,...,chi0n,chi1n,chi2n,chi3n,chi4n,hallKierAlpha,kappa1,kappa2,kappa3,Phi
0,54.046950,54.092,0.0,0.0,0.0,0.0,0.0,4.0,10.0,0.0,...,3.000000,1.250000,0.250000,0.250000,0.000000,-0.44,3.560000,2.560000,1.560000,2.278400
1,56.062600,56.108,0.0,0.0,1.0,0.0,0.0,4.0,12.0,0.0,...,2.991564,1.523603,0.288675,0.288675,0.000000,-0.26,3.740000,2.740000,1.740000,2.561900
2,58.005479,58.036,2.0,0.0,1.0,0.0,2.0,4.0,6.0,2.0,...,1.971197,0.804738,0.055556,0.055556,0.000000,-0.66,3.340000,2.340000,1.340000,1.953900
3,58.041865,58.080,1.0,0.0,1.0,0.0,1.0,4.0,10.0,1.0,...,2.692705,1.351057,0.166667,0.166667,0.000000,-0.33,3.670000,2.670000,1.670000,2.449725
4,59.017127,59.043,1.0,0.0,0.0,0.0,1.0,4.0,6.0,2.0,...,2.032285,0.844421,0.059761,0.059761,0.000000,-0.58,3.420000,2.420000,1.420000,2.069100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5215,780.429607,780.949,14.0,6.0,7.0,6.0,14.0,55.0,119.0,14.0,...,32.904204,20.930837,15.818454,15.818454,12.863616,-1.27,40.506603,15.080660,7.050935,11.106660
5216,780.429607,780.949,14.0,6.0,7.0,6.0,14.0,55.0,119.0,14.0,...,32.904204,20.940873,15.951629,15.951629,12.762329,-1.27,40.506603,15.080660,6.950374,11.106660
5217,788.854109,789.099,11.0,6.0,9.0,6.0,8.0,32.0,54.0,14.0,...,17.096813,8.930530,4.373121,4.373121,2.559391,-0.67,29.361918,12.697701,6.687388,11.650902
5218,790.869759,791.115,11.0,7.0,11.0,7.0,8.0,32.0,56.0,14.0,...,16.939261,9.247942,4.108352,4.108352,2.553586,-0.38,29.651626,14.119001,7.568060,13.082854
5219,794.445257,794.976,14.0,5.0,8.0,5.0,14.0,56.0,122.0,14.0,...,33.865239,21.326625,16.190510,16.190510,13.102687,-1.27,41.463559,15.641435,7.024560,11.581242

In [10]:
df4 = df[['Class']]

In [11]:
df_final = pd.concat([df3, df4], axis=1)
df_final.to_csv('irritation_MACCS.csv', index=False)