In [1]:
import numpy as np
import pandas as pd
import rdkit
from rdkit import Chem
from rdkit.Chem import rdMolDescriptors

In [21]:
descriptor_names = list(rdMolDescriptors.Properties.GetAvailableProperties())

get_descriptors = rdMolDescriptors.Properties(descriptor_names)

def smi_to_descriptors(smile):
    mol = Chem.MolFromSmiles(smile)
    descriptors = []
    if mol:
        descriptors = np.array(get_descriptors.ComputeProperties(mol))
    return descriptors

descriptor_names

['exactmw',
 'amw',
 'lipinskiHBA',
 'lipinskiHBD',
 'NumRotatableBonds',
 'NumHBD',
 'NumHBA',
 'NumHeavyAtoms',
 'NumAtoms',
 'NumHeteroatoms',
 'NumAmideBonds',
 'FractionCSP3',
 'NumRings',
 'NumAromaticRings',
 'NumAliphaticRings',
 'NumSaturatedRings',
 'NumHeterocycles',
 'NumAromaticHeterocycles',
 'NumSaturatedHeterocycles',
 'NumAliphaticHeterocycles',
 'NumSpiroAtoms',
 'NumBridgeheadAtoms',
 'NumAtomStereoCenters',
 'NumUnspecifiedAtomStereoCenters',
 'labuteASA',
 'tpsa',
 'CrippenClogP',
 'CrippenMR',
 'chi0v',
 'chi1v',
 'chi2v',
 'chi3v',
 'chi4v',
 'chi0n',
 'chi1n',
 'chi2n',
 'chi3n',
 'chi4n',
 'hallKierAlpha',
 'kappa1',
 'kappa2',
 'kappa3',
 'Phi']

In [3]:
df = pd.read_csv('../Data/all_data_log.csv')

In [4]:
df['descriptors'] = df.SMILES.apply(smi_to_descriptors)
df

,Unnamed: 0,SMILES,Name,logPerm,loss,DOI,descriptors
0,0,CC1CC2C3CCC(C3(CC(C2(C4(C1=CC(=O)C=C4)C)F)O)C)...,fluorometholone,5.135798,0.00,10.1002/jps.2600670614,"[376.20498762799997, 376.4680000000001, 4.0, 2..."
1,1,CC(C1=CC(=C(C=C1)C2=CC=CC=C2)F)C(=O)O,flurbiprofen,5.347108,0.00,10.1002/jps.2600830120,"[244.089957876, 244.265, 2.0, 1.0, 3.0, 1.0, 1..."
2,2,CC(C1=CC(=C(C=C1)C2=CC=CC=C2)F)C(=O)N,Flurbiprofen amide,5.393628,0.00,10.1002/jps.2600830120,"[243.105942288, 243.28099999999998, 2.0, 2.0, ..."
3,3,C(C(CO)O)O,glycerol,3.806662,0.00,10.1002/jps.2600770103,"[92.047344116, 92.09399999999998, 3.0, 3.0, 2...."
4,4,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,hydrocortisone,4.442651,0.00,10.1002/jps.2600670614,"[362.2093240599999, 362.46600000000007, 5.0, 3..."
...,...,...,...,...,...,...,...
123,123,CCCC1CC(N(C1)C)C(=O)NC(C2C(C(C(C(O2)SC)O)O)O)C...,Lincomycin,-0.105361,0.32,10.1016/j.ejps.2018.03.044,"[406.2137578079999, 406.54500000000013, 8.0, 5..."
124,124,COC1=CC2=C(C=CN=C2C=C1)C(C3CC4CCN3CC4C=C)O,Quinidine,2.161022,6.25,10.1016/j.ejps.2018.03.051,"[324.18377800799993, 324.4240000000001, 4.0, 1..."
125,125,C1CN=C(N1)NC2=C(C=CC3=NSN=C32)Cl,Tizanidine,3.850998,17.57,10.1016/j.ejps.2018.03.052,"[253.01889393599998, 253.718, 5.0, 2.0, 1.0, 2..."
126,126,CC(C1=NC=NC=C1F)C(CN2C=NC=N2)(C3=C(C=C(C=C3)F)F)O,Voriconazole,3.455686,15.34,10.1016/j.ejps.2018.03.053,"[349.11504472799993, 349.31600000000003, 6.0, ..."
127,127,CO,Methanol,6.815652,0.00,10.1016/S0378-5173(01)00902-27,"[32.026214748, 32.042, 1.0, 1.0, 0.0, 1.0, 1.0..."

In [5]:
df2=df[['descriptors', 'logPerm']]
df2

                                           descriptors   logPerm
0    [376.20498762799997, 376.4680000000001, 4.0, 2...  5.135798
1    [244.089957876, 244.265, 2.0, 1.0, 3.0, 1.0, 1...  5.347108
2    [243.105942288, 243.28099999999998, 2.0, 2.0, ...  5.393628
3    [92.047344116, 92.09399999999998, 3.0, 3.0, 2....  3.806662
4    [362.2093240599999, 362.46600000000007, 5.0, 3...  4.442651
..                                                 ...       ...
123  [406.2137578079999, 406.54500000000013, 8.0, 5... -0.105361
124  [324.18377800799993, 324.4240000000001, 4.0, 1...  2.161022
125  [253.01889393599998, 253.718, 5.0, 2.0, 1.0, 2...  3.850998
126  [349.11504472799993, 349.31600000000003, 6.0, ...  3.455686
127  [32.026214748, 32.042, 1.0, 1.0, 0.0, 1.0, 1.0...  6.815652

[128 rows x 2 columns]

In [33]:
for i in range(len(df['descriptors'][0])):
      df[f'{i}'] = df['descriptors'].apply(lambda x: x[i])
         
df3 = df.iloc [:, 7:50]
df3.columns = ['exactmw', 'amw', 'lipinskiHBA','lipinskiHBD', 'NumRotatableBonds', 'NumHBD', 'NumHBA', 'NumHeavyAtoms', 'NumAtoms', 'NumHeteroatoms', 'NumAmideBonds', 'FractionCSP3', 'NumRings', 'NumAromaticRings', 'NumAliphaticRings', 'NumSaturatedRings', 'NumHeterocycles', 'NumAromaticHeterocycles', 'NumSaturatedHeterocycles', 'NumAliphaticHeterocycles', 'NumSpiroAtoms', 'NumBridgeheadAtoms', 'NumAtomStereoCenters', 'NumUnspecifiedAtomStereoCenters', 'labuteASA', 'tpsa', 'CrippenClogP', 'CrippenMR', 'chi0v', 'chi1v', 'chi2v', 'chi3v', 'chi4v', 'chi0n', 'chi1n', 'chi2n', 'chi3n', 'chi4n', 'hallKierAlpha', 'kappa1', 'kappa2', 'kappa3', 'Phi']
df3

,exactmw,amw,lipinskiHBA,lipinskiHBD,NumRotatableBonds,NumHBD,NumHBA,NumHeavyAtoms,NumAtoms,NumHeteroatoms,...,chi0n,chi1n,chi2n,chi3n,chi4n,hallKierAlpha,kappa1,kappa2,kappa3,Phi
0,376.204988,376.468,4.0,2.0,1.0,2.0,4.0,27.0,56.0,5.0,...,16.458767,9.972554,8.703150,8.703150,7.183176,-1.33,19.006790,5.383489,1.997481,3.789735
1,244.089958,244.265,2.0,1.0,3.0,1.0,1.0,18.0,31.0,3.0,...,9.929579,5.670131,2.948361,2.948361,1.795098,-2.16,12.300954,5.001423,2.399040,3.417904
2,243.105942,243.281,2.0,2.0,3.0,1.0,1.0,18.0,32.0,3.0,...,10.059715,5.735200,3.004712,3.004712,1.816787,-2.16,12.300954,5.001423,2.399040,3.417904
3,92.047344,92.094,3.0,3.0,2.0,3.0,3.0,6.0,14.0,3.0,...,3.333205,1.707151,0.421498,0.421498,0.057735,-0.12,5.880000,3.084918,2.137732,3.023220
4,362.209324,362.466,5.0,3.0,2.0,3.0,5.0,26.0,56.0,5.0,...,15.701743,9.957047,8.653267,8.653267,7.281020,-1.04,18.329215,5.727623,2.138229,4.037801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,406.213758,406.545,8.0,5.0,7.0,5.0,8.0,27.0,61.0,9.0,...,16.485392,9.618716,5.655839,5.655839,4.132293,-0.42,22.864807,9.865355,5.144545,8.354423
124,324.183778,324.424,4.0,1.0,4.0,1.0,4.0,24.0,48.0,4.0,...,14.058926,8.682990,5.819484,5.819484,4.444306,-1.91,15.608011,6.187608,2.502406,4.024010
125,253.018894,253.718,5.0,2.0,1.0,2.0,6.0,16.0,24.0,7.0,...,8.196768,4.805416,2.294635,2.294635,1.545781,-1.40,9.799739,3.876645,1.595333,2.374382
126,349.115045,349.316,6.0,1.0,5.0,1.0,6.0,25.0,39.0,9.0,...,13.143084,7.372743,4.089727,4.089727,2.724196,-2.81,17.027366,6.595177,3.224982,4.491940
127,32.026215,32.042,1.0,1.0,0.0,1.0,1.0,2.0,6.0,1.0,...,1.447214,0.447214,0.000000,0.000000,0.000000,-0.04,1.960000,0.960000,-27.040000,0.940800

In [7]:
df4 = df[['logPerm']]
df4

      logPerm
0    5.135798
1    5.347108
2    5.393628
3    3.806662
4    4.442651
..        ...
123 -0.105361
124  2.161022
125  3.850998
126  3.455686
127  6.815652

[128 rows x 1 columns]

In [35]:
df_final = pd.concat([df3, df4], axis=1)
df_final
df_final.to_csv('descriptors.csv', index=False)